baseURL = 'https://camadkins.com/'
languageCode = 'en-us'
title = 'Cam Adkins'
theme = 'camadkins'

disableKinds = ['taxonomy', 'term']

[params]
  tagline = "What happens after the first version."
  signatureImage = "/cam-signature.png"
  [[params.links]]
    name = "blog"
    url = "https://blog.camadkins.com"
  [[params.links]]
    name = "github"
    url = "https://github.com/camadkins"
  [[params.links]]
    name = "notes"
    url = "https://notes.camadkins.com"

[markup.goldmark.renderer]
  unsafe = true
